apiVersion: v1
kind: Service
metadata:
  name: flowise-service
  labels:
    app: flowise
spec:
  type: LoadBalancer
  selector:
    app: flowise
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
